# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 25 Oct 2023 21:13:39 +0000
*	@ALL	1
community:*	@user	8
*	@admin	16
