<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: pudlovskij
 * Date: Tue, 21 Nov 2023 12:49:37 +0300
 */

$conf['title'] = 'AI instruments';
$conf['lang'] = 'ru';
$conf['license'] = '0';
$conf['savedir'] = '/app/www/public/data';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
