# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 25 Oct 2023 21:13:39 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

pudlovskij:$2y$10$jFGpmhWjip5SXKT3E2XhFOuJzRhSsgfM5B8BFJKhWeTjHVoMhHILO:Pudlovskij:pudlovskij_aa_21@mf.grsu.by:admin,user
pudlovskijj2:$2y$10$u68zfc2gam1wOfWMKTD7iu7X3R56B3v.01bbRQWEIUKGMKpygIyzG:Pudlovskij2:pudlovskiy2018@mail.ru:user
pudlovskij3:$2y$10$U6fm0D2Y4kvGrLEp1yvthOUlFrLzOV5aVEj9vh/hj1KP5EugMGgey:Pudlovskij3:pudlovskij3@mail.ru:user
pudlovskij4:$2y$10$r2gqxysnQwNuxMZBVxwDJu5AIoyBWzbkPvg7RtLSVAWhQ/NdgSruK:Pudlovskij4:pudlovskiy2016@mail.ru:user
